<?php

/**
 * @file 
 * Main install.
 */

/**
 * Implements hook_enable().
 */
function helium_exporter_enable() {
  // Create a system variable to hold settings
  // for Subject and Object (cvterms) to use when 
  // creating pedigree tree.

  // Default to 0 - frontend will remind user that
  // module has not been completely configured.
  variable_set('helium_exporter_pedigree_relations', 0);
}